travis:
  secure:
    BINSTAR_TOKEN: kj6WMh+eY99Amy6CmbnQpQvo8vLvrrXLU4hv2uMUGxZl/PjsVv7lc/3yUJZ4POgUqolT0CF9HfcivQGgNSDqI54BUgnwpcuoQI/POfnJ9skAzq4ayzo9HEcJn7N/wHXbZgzJjqamFPe+U8OI54KzGsnTsReo+XdCDK7QCLYD1PyOg1FPBzsg0x69db6UkVxkKS1GE7uU4LRJPRYW3uFwBL81WHKJnsAQycNdyiSDYESvFbeZUFhSS0o8WIdUZhSqRLBOdtAh3taNGVHtA7vzOcMb+0nG0xBfj0ZyJADrBIWUEa1f5+D+VqsnyoE8jldw7rOlpNmQhO5ZVvYQwmRTa0a8mZsNYWxuaWNMmbsJ1KI4UZe7vhopu/n+IREg8zvcZZo7V1Oi25LtQxmEQjf9J3t32A9Py2c24ervSabtim6NXEEkEP5vyJ0BTEVhNoF+b3wxDllyBY3hMYl6qRnweRvEoFo8FdSKHHlDeo72MaPcs4VVZHFRsPLPZsDZZcghAPjTOznq0sFLHU6Y/yttj8JN7DCPFTfQhTvVQWSi5CuK82nCnGDTaov0ZmI1zJQZC/xO/JzE1bKLAYY/zmost/E5kfzXSVC4kXJJCTWoo4q8drE4E6gdmK7QntuzmVHM379eCAo4pmCi7o6KTDK/P9wP2Opqy8Dg13B8Qi8kRIs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
